/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackAwbRouteImport } from './routes/track.$awb'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedShipmentsNewRouteImport } from './routes/_authenticated/shipments.new'
import { Route as AuthenticatedShipmentsIdRouteImport } from './routes/_authenticated/shipments.$id'
import { Route as AuthenticatedMastersShippersRouteImport } from './routes/_authenticated/masters.shippers'
import { Route as AuthenticatedMastersRatesRouteImport } from './routes/_authenticated/masters.rates'
import { Route as AuthenticatedMastersConsigneesRouteImport } from './routes/_authenticated/masters.consignees'
import { Route as AuthenticatedMastersAwbStockRouteImport } from './routes/_authenticated/masters.awb-stock'
import { Route as AuthenticatedMastersAirlinesRouteImport } from './routes/_authenticated/masters.airlines'
import { Route as AuthenticatedMastersAgentsRouteImport } from './routes/_authenticated/masters.agents'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackAwbRoute = TrackAwbRouteImport.update({
  id: '/track/$awb',
  path: '/track/$awb',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShipmentsNewRoute =
  AuthenticatedShipmentsNewRouteImport.update({
    id: '/shipments/new',
    path: '/shipments/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShipmentsIdRoute =
  AuthenticatedShipmentsIdRouteImport.update({
    id: '/shipments/$id',
    path: '/shipments/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersShippersRoute =
  AuthenticatedMastersShippersRouteImport.update({
    id: '/masters/shippers',
    path: '/masters/shippers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersRatesRoute =
  AuthenticatedMastersRatesRouteImport.update({
    id: '/masters/rates',
    path: '/masters/rates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersConsigneesRoute =
  AuthenticatedMastersConsigneesRouteImport.update({
    id: '/masters/consignees',
    path: '/masters/consignees',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersAwbStockRoute =
  AuthenticatedMastersAwbStockRouteImport.update({
    id: '/masters/awb-stock',
    path: '/masters/awb-stock',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersAirlinesRoute =
  AuthenticatedMastersAirlinesRouteImport.update({
    id: '/masters/airlines',
    path: '/masters/airlines',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersAgentsRoute =
  AuthenticatedMastersAgentsRouteImport.update({
    id: '/masters/agents',
    path: '/masters/agents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/track/$awb': typeof TrackAwbRoute
  '/masters/agents': typeof AuthenticatedMastersAgentsRoute
  '/masters/airlines': typeof AuthenticatedMastersAirlinesRoute
  '/masters/awb-stock': typeof AuthenticatedMastersAwbStockRoute
  '/masters/consignees': typeof AuthenticatedMastersConsigneesRoute
  '/masters/rates': typeof AuthenticatedMastersRatesRoute
  '/masters/shippers': typeof AuthenticatedMastersShippersRoute
  '/shipments/$id': typeof AuthenticatedShipmentsIdRoute
  '/shipments/new': typeof AuthenticatedShipmentsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/track/$awb': typeof TrackAwbRoute
  '/masters/agents': typeof AuthenticatedMastersAgentsRoute
  '/masters/airlines': typeof AuthenticatedMastersAirlinesRoute
  '/masters/awb-stock': typeof AuthenticatedMastersAwbStockRoute
  '/masters/consignees': typeof AuthenticatedMastersConsigneesRoute
  '/masters/rates': typeof AuthenticatedMastersRatesRoute
  '/masters/shippers': typeof AuthenticatedMastersShippersRoute
  '/shipments/$id': typeof AuthenticatedShipmentsIdRoute
  '/shipments/new': typeof AuthenticatedShipmentsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/track/$awb': typeof TrackAwbRoute
  '/_authenticated/masters/agents': typeof AuthenticatedMastersAgentsRoute
  '/_authenticated/masters/airlines': typeof AuthenticatedMastersAirlinesRoute
  '/_authenticated/masters/awb-stock': typeof AuthenticatedMastersAwbStockRoute
  '/_authenticated/masters/consignees': typeof AuthenticatedMastersConsigneesRoute
  '/_authenticated/masters/rates': typeof AuthenticatedMastersRatesRoute
  '/_authenticated/masters/shippers': typeof AuthenticatedMastersShippersRoute
  '/_authenticated/shipments/$id': typeof AuthenticatedShipmentsIdRoute
  '/_authenticated/shipments/new': typeof AuthenticatedShipmentsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/dashboard'
    | '/track/$awb'
    | '/masters/agents'
    | '/masters/airlines'
    | '/masters/awb-stock'
    | '/masters/consignees'
    | '/masters/rates'
    | '/masters/shippers'
    | '/shipments/$id'
    | '/shipments/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/dashboard'
    | '/track/$awb'
    | '/masters/agents'
    | '/masters/airlines'
    | '/masters/awb-stock'
    | '/masters/consignees'
    | '/masters/rates'
    | '/masters/shippers'
    | '/shipments/$id'
    | '/shipments/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/track/$awb'
    | '/_authenticated/masters/agents'
    | '/_authenticated/masters/airlines'
    | '/_authenticated/masters/awb-stock'
    | '/_authenticated/masters/consignees'
    | '/_authenticated/masters/rates'
    | '/_authenticated/masters/shippers'
    | '/_authenticated/shipments/$id'
    | '/_authenticated/shipments/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrackAwbRoute: typeof TrackAwbRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$awb': {
      id: '/track/$awb'
      path: '/track/$awb'
      fullPath: '/track/$awb'
      preLoaderRoute: typeof TrackAwbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shipments/new': {
      id: '/_authenticated/shipments/new'
      path: '/shipments/new'
      fullPath: '/shipments/new'
      preLoaderRoute: typeof AuthenticatedShipmentsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shipments/$id': {
      id: '/_authenticated/shipments/$id'
      path: '/shipments/$id'
      fullPath: '/shipments/$id'
      preLoaderRoute: typeof AuthenticatedShipmentsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/shippers': {
      id: '/_authenticated/masters/shippers'
      path: '/masters/shippers'
      fullPath: '/masters/shippers'
      preLoaderRoute: typeof AuthenticatedMastersShippersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/rates': {
      id: '/_authenticated/masters/rates'
      path: '/masters/rates'
      fullPath: '/masters/rates'
      preLoaderRoute: typeof AuthenticatedMastersRatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/consignees': {
      id: '/_authenticated/masters/consignees'
      path: '/masters/consignees'
      fullPath: '/masters/consignees'
      preLoaderRoute: typeof AuthenticatedMastersConsigneesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/awb-stock': {
      id: '/_authenticated/masters/awb-stock'
      path: '/masters/awb-stock'
      fullPath: '/masters/awb-stock'
      preLoaderRoute: typeof AuthenticatedMastersAwbStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/airlines': {
      id: '/_authenticated/masters/airlines'
      path: '/masters/airlines'
      fullPath: '/masters/airlines'
      preLoaderRoute: typeof AuthenticatedMastersAirlinesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/agents': {
      id: '/_authenticated/masters/agents'
      path: '/masters/agents'
      fullPath: '/masters/agents'
      preLoaderRoute: typeof AuthenticatedMastersAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMastersAgentsRoute: typeof AuthenticatedMastersAgentsRoute
  AuthenticatedMastersAirlinesRoute: typeof AuthenticatedMastersAirlinesRoute
  AuthenticatedMastersAwbStockRoute: typeof AuthenticatedMastersAwbStockRoute
  AuthenticatedMastersConsigneesRoute: typeof AuthenticatedMastersConsigneesRoute
  AuthenticatedMastersRatesRoute: typeof AuthenticatedMastersRatesRoute
  AuthenticatedMastersShippersRoute: typeof AuthenticatedMastersShippersRoute
  AuthenticatedShipmentsIdRoute: typeof AuthenticatedShipmentsIdRoute
  AuthenticatedShipmentsNewRoute: typeof AuthenticatedShipmentsNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMastersAgentsRoute: AuthenticatedMastersAgentsRoute,
  AuthenticatedMastersAirlinesRoute: AuthenticatedMastersAirlinesRoute,
  AuthenticatedMastersAwbStockRoute: AuthenticatedMastersAwbStockRoute,
  AuthenticatedMastersConsigneesRoute: AuthenticatedMastersConsigneesRoute,
  AuthenticatedMastersRatesRoute: AuthenticatedMastersRatesRoute,
  AuthenticatedMastersShippersRoute: AuthenticatedMastersShippersRoute,
  AuthenticatedShipmentsIdRoute: AuthenticatedShipmentsIdRoute,
  AuthenticatedShipmentsNewRoute: AuthenticatedShipmentsNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrackAwbRoute: TrackAwbRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
